apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: mynginx
    image: shivam286/newnginx:12
    ports:
    - containerPort: 80
